on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  main-CI-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run commands in backend directory
        run: |
          cd ./src/nexus-api
          npm install
          npm run test
